---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: deploy insureme application
    command: sudo docker run -itd -p 8081:8081 --name insure-me shubhamkushwah123/insure-me:1.0
